ALTER TABLE uploaded_pdfs ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE uploaded_pdfs ADD COLUMN IF NOT EXISTS file_hash VARCHAR(255);

ALTER TABLE projects DROP COLUMN IF EXISTS timeline;
ALTER TABLE projects ADD COLUMN timeline JSONB DEFAULT '[]'::jsonb;
